!obj:pylearn2.train.Train {
    dataset: !obj:contest_dataset.ContestDataset {
        which_set: 'train',
        start: 0,
        stop: 3400
        },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [!obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 7,
                     irange: 0.
                 }
                ],
        nvis: 2304,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 64,
        learning_rate: 0.100000,
        monitoring_dataset:
            {
                'train' : !obj:contest_dataset.ContestDataset {
                              which_set: 'train',
                              start: 0,
                              stop: 3400
                              },
                'valid' : !obj:contest_dataset.ContestDataset {
                              which_set: 'train',
                              start: 3400,
                              stop:  4150
                          }
            },
        cost: !obj:pylearn2.costs.cost.MethodCost {
                method: 'cost_from_X',
                supervised: 1
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass"
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "1layerSoftmax_LR0.1_best.pkl"
        },
    ],
    save_path: "1layerSoftmax_LR0.1.pkl",
    save_freq: 1
    }